let names = [
    "abu road abr",
    "adilabad adb",
    "adoni ad",
    "adra adra",
    "agartala agtl",
    "agra fort af",
    "agra cantt. agc",
    "ahmadnagar ang",
    "ahmedabad adi",
    "ajmer aii",
    "ajni ajni",
    "akola ak",
    "aligarh aljn",
    "alipurduar jn. apdj",
    "allahabad ald",
    "alappuzha allp",
    "alnawar jn. lwr",
    "aluva awy",
    "alwar awr",
    "amalner an",
    "amb andavra aadr",
    "ambala cantt. umb",
    "ambikapur abkp",
    "amla amla",
    "amritsar asr",
    "anakapalle akp",
    "anand annd",
    "anand nagar andn",
    "anand vihar terminus anvt",
    "anantapur atp",
    "angul angl",
    "annavaram anv",
    "anuppur apr",
    "ara ara",
    "arakkonam ajj",
    "arsikere ask",
    "asansol asn",
    "aunrihar arj",
    "aurangabad awb",
    "ayodhya ay",
    "azamgarh amh",
    "azimganj jn. az",
    "badarpur bpb",
    "badnera jn. bd",
    "bagalkot bgk",
    "baghpat road bpm",
    "baidyanathdham bdme",
    "bakthiyarpur bkp",
    "balasore bls",
    "balaghat btc",
    "balangir blgr",
    "balugaon balu",
    "balurghat blgt",
    "balharshah bpq",
    "ballia bui",
    "banarhat bnq",
    "banda jn. bnda",
    "bandel jn. bdc",
    "bandikui jn. bki",
    "bandra (t) bdts",
    "bangalore city sbc",
    "bangalore cantt. bnc",
    "bangarapet bwt",
    "bangriposi bgy",
    "bankura bqa",
    "banmankhi bnki",
    "bapatla bpp",
    "barabanki jn. bbk",
    "barabil bbn",
    "baran baz",
    "barauni jn. bju",
    "baraut btu",
    "barapalli brpl",
    "barddhaman jn. bwn",
    "bareilly be",
    "bargarh road brga",
    "barhni bny",
    "barkakana brka",
    "barmer bme",
    "barog bof",
    "barsoi boe",
    "barwadih brwd",
    "basar bsx",
    "basti bst",
    "bathinda jn. bti",
    "bayana bxn",
    "beas beas",
    "beawar ber",
    "belapur bap",
    "belgaum bgm",
    "bellary jn. bay",
    "bettiah bth",
    "betul bzu",
    "bhadohi boy",
    "bhadrak bhc",
    "bhagalpur bgp",
    "bhagat ki kothi bgki",
    "bharatpur bte",
    "bharuch bh",
    "bhatapara byt",
    "bhatkal btjl",
    "bhatni btt",
    "bhavnagar (t) bvc",
    "bhawanipatna bwpi",
    "bhilwara bhl",
    "bhimavaram jn. bvrm",
    "bhimavaram town bvrt",
    "bhind bix",
    "bhiwani bnw",
    "bhopal bpl",
    "bhubaneswar bbs",
    "bhuj bhuj",
    "bhusaval bsl",
    "bijapur bjp",
    "bijnor bjo",
    "bikaner bkn",
    "bilaspur jn. bsp",
    "bina bina",
    "binnaguri bnv",
    "birur rrb",
    "bitragunta bttr",
    "biyavara rajgarh brrg",
    "bobbili vbl",
    "boinda bona",
    "barapalli brpl",
    "baghbahar bgbr",
    "bokaro steel city bksc",
    "bolpur shantiniketan bhp",
    "borivali bvi",
    "botad btd",
    "budaun bem",
    "bundi budi",
    "burhanpur bau",
    "burhwal buw",
    "buxar bxr",
    "canacona cno",
    "chakia caa",
    "chakki bank chkb",
    "chakradharpur ckp",
    "chalisgaon csn",
    "champa cph",
    "chandausi ch",
    "chanderiya cna",
    "chandigarh cdg",
    "chandil cni",
    "chandrapur cd",
    "chandrapura crp",
    "chaparmukh cpk",
    "chatrapur cap",
    "chengalpattu jn. cgl",
    "chengannur cngr",
    "chennai central mas",
    "chennai egmore ms",
    "chhapra cpr",
    "chhindwara cwa",
    "chidambaram cdm",
    "chikjajur jru",
    "chiplun chi",
    "chirala clx",
    "chitrakootdham karvi cktd",
    "chittaranjan crj",
    "chittaurgarh cor",
    "chittoor cto",
    "chopan cpu",
    "chunar car",
    "churu cur",
    "coimbatore jn. cbe",
    "coonoor onr",
    "cuddalore port cupj",
    "cuddapah hx",
    "cuttack ctc",
    "dadar dr",
    "dahanu road drd",
    "dahod dhd",
    "dalgaon dlo",
    "daltonganj dto",
    "dallirajhara drz",
    "damoh dmo",
    "danapur dnr",
    "darbhanga dbg",
    "daund dd",
    "davangere dvg",
    "dehradun ddn",
    "dehri-on-sone dos",
    "delhi dli",
    "new delhi ndls",
    "delhi cantt. dec",
    "delhi sarai rohilla dee",
    "delhi shahdara dsa",
    "deoriasadar deos",
    "devlali dvl",
    "dhamangaon dmn",
    "dhanbad dhn",
    "dharmabad dab",
    "dharmanagar dmr",
    "dharmapuri dpj",
    "dharmavaram dmm",
    "dharwad dwr",
    "dhasa das",
    "dhaulpur dho",
    "dhenuanal dnul",
    "dhola dlj",
    "dhone dhne",
    "dhrangadhra dhg",
    "dhubri dbb",
    "dhuri dui",
    "dibrugarh dbrg",
    "dibrugarh town dbrt",
    "digha dgha",
    "dildarnagar dln",
    "dimapur dmv",
    "dindigul jn. dg",
    "dongargarh dgg",
    "dornakal dkj",
    "dungarpur dnrp",
    "durg durg",
    "durgapur dgr",
    "duvvada dvd",
    "dwarka dwk",
    "eluru ee",
    "ernakulam jn. ers",
    "ernakulam town ern",
    "erode ed",
    "etawah etw",
    "faizabad fd",
    "faridabad fdb",
    "farrukhabad fbd",
    "fatehabad chand ftd",
    "fatehpur ftp",
    "fatuha fut",
    "fazilka fka",
    "firozabad fzd",
    "firozpur city fzp",
    "firozpur cantt. fzr",
    "forbesganj fbg",
    "furkating fkg",
    "gadag gdg",
    "gajraula gjl",
    "gandhidham gim",
    "gandhinagar gadj",
    "gangapur city ggc",
    "garwa road ghd",
    "gaya gaya",
    "gevra road gad",
    "ghatsila gts",
    "ghaziabad gzb",
    "goalpara town glpt",
    "godhra gda",
    "gola gokarannath gk",
    "gonda gd",
    "gondia g",
    "gooty gy",
    "gorakhpur gkp",
    "gossaingaon hat gogh",
    "gudivada gdv",
    "gudur gdr",
    "gulbarga gr",
    "guna guna",
    "guntakal gtl",
    "guntur gnt",
    "gurgaon ggn",
    "guruvayur guv",
    "guwahati ghy",
    "gwalior gwl",
    "gyanpur road gyn",
    "habibganj hbj",
    "hajipur hjp",
    "haldia hlz",
    "haldibari hdb",
    "hamiltonganj hoj",
    "hanumangarh hmh",
    "hapa hapa",
    "hapur hpu",
    "harda hd",
    "haridwar hw",
    "harihar hrr",
    "harpalpur hpp",
    "hasimara hsa",
    "hatia hte",
    "hazur sahib nanded ned",
    "hilsa hil",
    "himmat nagar hmt",
    "hindupur hup",
    "hingoli hnl",
    "hisar hsr",
    "hoshangabad hbd",
    "hospet hpt",
    "hosur hsra",
    "howbadh hbg",
    "howrah hwh",
    "hubli ubl",
    "hyderabad hyb",
    "igatpuri igp",
    "indara iaa",
    "indore indb",
    "islampur ipr",
    "itarsi et",
    "jabalpur jbp",
    "jagdalpur jdb",
    "jaipur jp",
    "jaypur jyp",
    "jaisalmer jsm",
    "jajpur keonjhar road jjkr",
    "jakhal jhl",
    "jalamb jm",
    "jalandhar cantt. jrc",
    "jalandhar city juc",
    "jalgaon jl",
    "jalna j",
    "jalpaiguri jpg",
    "jamalpur jmp",
    "jammu tawi jat",
    "jamnagar jam",
    "janghai jnh",
    "jasidih jsme",
    "jaunpur jn. jnu",
    "jaynagar jyg",
    "jetalsar jlr",
    "jhajha jaj",
    "jhansi jhs",
    "jhargram jgm",
    "jharsuguda jsg",
    "jind jind",
    "jodhpur ju",
    "jogbani jbn",
    "jolarpettai jtj",
    "jorhat jt",
    "junagarh jn. jnd",
    "kacheguda kcg",
    "kakinada port coa",
    "kalchini kcf",
    "kalka klk",
    "kalol kll",
    "kalyan kyn",
    "kamakhya kyq",
    "kanchipuram cj",
    "kandhla kql",
    "kanniyakumari cape",
    "kannur can",
    "kanpur central cnb",
    "kanpur anwarganj cpa",
    "kaptanganj cpj",
    "karaikal kik",
    "karaikkudi jn. kkdi",
    "karimganj kxj",
    "karnal kun",
    "karur krr",
    "karwar kawr",
    "kasaragod kgq",
    "kasganj ksj",
    "kathgodam kgm",
    "katihar kir",
    "katni kte",
    "katni murwara kmz",
    "katpadi kpd",
    "katwa kwae",
    "station name code station name code station name code station name code",
    "44",
    "station code index",
    "tag-13",
    "kazipet kzj",
    "kesinga ksng",
    "kendujhargarh kdjr",
    "khagaria kgg",
    "khalilabad kld",
    "khammam kmt",
    "khandwa knw",
    "kharagpur kgp",
    "khekra kex",
    "khurda road kur",
    "khurja krj",
    "kishanganj kne",
    "kishangarh ksg",
    "kiul kiul",
    "kochuveli kcvl",
    "kodaikanal road kqn",
    "kolkata koaa",
    "kollam qln",
    "kopergaon kpg",
    "koraput krpu",
    "korba krba",
    "kota kota",
    "kotdwara ktw",
    "kot kapura kkp",
    "kottayam ktym",
    "kozhikode clt",
    "krishnanagar city knj",
    "krishnarajapuram kjm",
    "kumarghat kugt",
    "kumbakonam kmu",
    "kundapura kuda",
    "kurduwadi kwv",
    "kurnool town krnt",
    "kurukshetra kkde",
    "lakhimpur lmp",
    "laksar lrj",
    "lalgarh lgh",
    "lalgola lgl",
    "lalitpur lar",
    "lalkuan jn. lku",
    "latur lur",
    "ledo ledo",
    "loharu lhu",
    "lokmanya tilak (t) ltt",
    "lonavla lnl",
    "londa ld",
    "lower halflong lfg",
    "lucknow ljn/lko",
    "ludhiana ldh",
    "lumding lmg",
    "luni luni",
    "machilipatnam mtm",
    "madarihat mdt",
    "maddur mad",
    "madgaon (goa) mao",
    "madhubani mbi",
    "madhupur mdp",
    "madurai jn. mdu",
    "mahasamund msmd",
    "mahbubnagar mbnr",
    "mahuva mhv",
    "muniguda mngd",
    "mahesana msh",
    "mahoba mba",
    "mailani mln",
    "maksi mkc",
    "malda town mldt",
    "manamadurai mnm",
    "manduadih muv",
    "mangalore central maq",
    "mangalore jn. majn",
    "manikpur mkp",
    "mankapur mur",
    "manmad mmr",
    "mannargudi mq",
    "mansi mne",
    "manu manu",
    "mariani mxn",
    "marwar jn. mj",
    "mathura mtj",
    "mau mau",
    "mayiladuturai jn. mv",
    "meerut city mtc",
    "merta road mtd",
    "mettupalayam mtp",
    "midnapore mdn",
    "miraj mrj",
    "miryalaguda mrga",
    "mirzapur mzp",
    "moga mof",
    "mokama mka",
    "pudukottai pdkt",
    "pulgaon plo",
    "pune jn. pune",
    "puranpur pp",
    "puri puri",
    "purna pau",
    "purnia prna",
    "purulia prr",
    "radhikapur rdp",
    "rae bareli rbl",
    "raichur rc",
    "raigarh rig",
    "raipur r",
    "rajahmundry rjy",
    "raja-ka-sahaspur rjk",
    "raja-ki-mandi rkm",
    "rajendranagar rjq",
    "rajgir rgd",
    "rajkot rjt",
    "rajnandgaon rjn",
    "rajpura rpj",
    "ramagundam rdm",
    "ramanathapuram rmd",
    "rameswaram rmm",
    "ramnagar rmr",
    "rampur jn. rmu",
    "rampurhat rph",
    "ranaghat rha",
    "ranchi rnc",
    "rangapara north rpan",
    "rangiya rny",
    "raninagar roj",
    "ratangarh rtgh",
    "ratlam rtm",
    "ratnagiri rn",
    "rawatganj rj",
    "raxaul rxl",
    "rayagada rgda",
    "renigunta ru",
    "rewa rewa",
    "rewari re",
    "ringus rgs",
    "rohtak rok",
    "roorkee rk",
    "rourkela rou",
    "sadulpur sdlp",
    "sagar jambagaru srf",
    "sagauli sgl",
    "sagour sgo",
    "saharanpur sre",
    "saharsa shc",
    "sahibganj sbg",
    "sai nagar shirdi snsi",
    "salem sa",
    "salempur sru",
    "samalkot slo",
    "samastipur spj",
    "sambalpur sbp",
    "sambalpur city sbpy",
    "samdari smr",
    "samuktala road amta",
    "sangli sli",
    "santragachi src",
    "sarnath srnt",
    "satara str",
    "satna sta",
    "sattenapalle sap",
    "sawaimadhopur swm",
    "sawantwadi road swv",
    "sealdah sdah",
    "secunderabad sc",
    "sengottai sct",
    "sensoa scf",
    "sewagram segm",
    "shahabad sdb",
    "shahganj shg",
    "shahjahanpur spn",
    "shahpur patoree spp",
    "shaktinagar sktn",
    "shalimar shm",
    "shamgarh sgz",
    "shamli smql",
    "shikohabad skb",
    "shimla sml",
    "shimoga town smet",
    "shivpuri svpi",
    "shoranur jn. srr",
    "shri mahabirji smbj",
    "sihor gujarat sojn",
    "sikar sikr",
    "moradabad mb",
    "motihari mki",
    "mudkhed mue",
    "mughalsarai mgs",
    "mumbai central bct",
    "mumbai cst cstm",
    "muniguda mngd",
    "muri muri",
    "murkeongselek mzs",
    "murtajapur mzr",
    "muzaffar nagar moz",
    "muzaffarpur mfp",
    "mysore mys",
    "nabadwipdham ndae",
    "nadiad nd",
    "nadikudi ndkd",
    "nagappattinam ngt",
    "nagarkata nkb",
    "nagarsol nsl",
    "nagbhir nab",
    "nagda nad",
    "nagercoil jn. ncj",
    "nagore ncr",
    "nagpur ngp",
    "nagrakata nkb",
    "nainpur nir",
    "najibabad nbd",
    "nalanda nld",
    "nalgonda nlda",
    "namakkal nmkl",
    "nandalur nre",
    "nandgaon ngn",
    "nandurbar ndb",
    "nandyal ndl",
    "nangal dam nldm",
    "narkatiaganj nke",
    "narasapur ns",
    "narsingpur nu",
    "narwana nrw",
    "nasik road nk",
    "naugarh nuh",
    "nellore nlr",
    "netaji subhash chandra bose gomoh gmo",
    "new alipurduar noq",
    "new bongaigaon nbq",
    "new coochbehar ncb",
    "new delhi ndls",
    "new farakka nfk",
    "new jalpaiguri njp",
    "newmal jn. nmz",
    "new tinsukia ntsk",
    "nidadavolu ndd",
    "nidamangalam nmj",
    "nidubrolu ndo",
    "nimach nmh",
    "nizamabad nzb",
    "nizamuddin nzm",
    "noli noli",
    "north lakhimpur nlp",
    "odlabari odb",
    "okha okha",
    "ongole ogl",
    "orai orai",
    "pachora pc",
    "palani plni",
    "palanpur pnu",
    "palasa psa",
    "palakkad pgt",
    "palakkad town pgtn",
    "paliakalan plk",
    "pandharapur pvr",
    "panipat pnp",
    "paradeep prdp",
    "parasnath pnme",
    "panvel pnvl",
    "parbhani pbn",
    "parvatipuram town pvpt",
    "pathankot ptk",
    "patiala pta",
    "patna pnbe",
    "patna sahib pnc",
    "phalodi plc",
    "phaphamau pfm",
    "phulera fl",
    "pilibhit pbe",
    "pipariya ppi",
    "podanur ptj",
    "porbandar pbr",
    "pratapgarh pbh",
    "puducherry pdy",
    "silchar scl",
    "silghat shtt",
    "siliguri sguj",
    "siliguri town sgut",
    "simaluguri slgr singrauli sgrl",
    "sirpur kagaznagar skzr",
    "sirsa ssa",
    "siswa bazar sbz",
    "sitamarhi smi",
    "sitapur city spc",
    "sitapur cantt. scc",
    "siuri suri",
    "siwan sv",
    "sojat road sod",
    "solan sol",
    "solapur sur",
    "somnath smnh",
    "sompeta spt",
    "sonpur see",
    "sri chhatrapati shahu maharaj (t) csmt",
    "sri dungargarh sdgh",
    "sriganga nagar sgnr",
    "srikakulam road che",
    "sri sathyasai prashanti nilayam sspn",
    "sujangarh sujh",
    "sultanpur sln",
    "surat st",
    "suratgarh sog",
    "surathkal sl",
    "surendra nagar sunr",
    "tadepalligudem tdd",
    "tambaram tbm",
    "tatanagar tata",
    "thalassery tly",
    "tenali tel",
    "tenkasi ts",
    "tezpur tztb",
    "thanjavur tj",
    "thiruvarur. tvr",
    "tiruchchirappalli jn. tpj",
    "tiruchendur tcn",
    "tirunelveli ten",
    "tirupati tpty",
    "tiruppur tup",
    "tirur tir",
    "titlagarh tig",
    "thrisur tcr",
    "thiruvananthapuram tvc",
    "tiruvannamalai tnm",
    "tumsar road tmr",
    "tundla tdl",
    "tuni tuni",
    "tuticorin tn",
    "udaipur city udz",
    "udhampur uhp",
    "udhna udn",
    "udupi ud",
    "ujjain ujn",
    "una una",
    "unchahar ucr",
    "unnao on",
    "vadakara bdj",
    "vadodara brc",
    "valsad bl",
    "vanchi maniyachchi jn. mej",
    "varanasi bsb",
    "varkala vak",
    "vasai road bsr",
    "vasco-da-gama vsg",
    "velankanni vlkn",
    "veraval vrl",
    "vidisha bhs",
    "vijayawada bza",
    "villupuram jn. vm",
    "viramgam vg",
    "virudunagar jn. vpt",
    "visakhapatnam vskp",
    "vizianagaram vzm",
    "vriddhachalam jn. vri",
    "wadi wadi",
    "wankaner wkr",
    "warangal wl",
    "wardha jn. wr",
    "yesvantpur ypr",
    "zafarabad zbd",
];

let sortedNames = names.sort();
//reference
let input = document.getElementById("input");
//Execute function on keyup
input.addEventListener("keyup", (e) => {
  //loop through above array
  //Initially remove all elements ( so if user erases a letter or adds new letter then clean previous outputs)
  removeElements();
  for (let i of sortedNames) {
    //convert input to lowercase and compare with each string
    if (
      i.toLowerCase().startsWith(input.value.toLowerCase()) &&
      input.value != ""
    ) {
      //create li element
      let listItem = document.createElement("li");
      //One common class name
      listItem.classList.add("list-items");
      listItem.style.cursor = "pointer";
      listItem.setAttribute("onclick", "displayNames('" + i + "')");
      //Display matched part in bold
      let word = "<b>" + i.substr(0, input.value.length) + "</b>";
      word += i.substr(input.value.length);
      //display the value in array
      listItem.innerHTML = word;
      document.querySelector(".list").appendChild(listItem);
    }
  }
});
function displayNames(value) {
  input.value = value;
  removeElements();
}
function removeElements() {
  //clear all the item
  let items = document.querySelectorAll(".list-items");
  items.forEach((item) => {
    item.remove();
});
}